package by.epam.courierexchange.controller.command;


public enum CommandType {
    DEFAULT,
    LOGIN,
    LOGOUT,
    CHANGE_LOCALE,
    SIGN_UP,
    UPDATE_PROFILE,
    CREATE_NEW_ORDER,
    UPDATE_PASSWORD,
    CHANGE_PASSWORD,
    CONFIRM_PROFILE,
    CHANGE_USER_ROLE,

    GO_TO_NEW_PASS,
    GO_TO_NEW_ORDER_PAGE,
    GO_TO_LOGIN,
    GO_TO_SIGN_UP,
    GO_TO_FORGOT_PASS,
    GO_TO_USER_PROFILE,
    GO_TO_USER_ALL_ORDERS,
    GO_TO_MY_ORDERS_PAGE,
    GO_TO_HISTORY_PAGE,
    START_PAGE
}
